title: "Test Site"
name: "Prasad Matukumilli"
email: "your@email.com"
description: >-
  Researcher in lattice dynamics, anharmonic phonons, and superionic conductors.

# social links
social_links:
  github: matukumilli
  linkedin: your-linkedin-username
  twitter: your-twitter-handle
  scholar: your-google-scholar-id
  orcid: your-orcid-id
theme: jekyll-theme-minimal
