source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8"

gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-paginate"
gem "jekyll-scholar"
gem "jekyll-toc"
gem "jekyll-include-cache"
gem "jekyll-remote-theme"
gem "jekyll-regex-replace"
gem "jekyll-email-protect"
gem "jekyll-get-json"
gem "jekyll-minifier"
gem "jekyll-imagemagick"
gem "jekyll-archives"
gem "jekyll-paginate-v2"
gem "jekyll-jupyter-notebook"
gem "jekyll-tabs"

# Requirements for notebooks & distill
gem "kramdown-parser-gfm"
gem "rouge"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-paginate"
  gem "jekyll-scholar"
  gem "jekyll-toc"
  gem "jekyll-include-cache"
  gem "jekyll-remote-theme"
  gem "jekyll-regex-replace"
  gem "jekyll-email-protect"
  gem "jekyll-get-json"
  gem "jekyll-minifier"
  gem "jekyll-imagemagick"
  gem "jekyll-archives"
  gem "jekyll-paginate-v2"
  gem "jekyll-jupyter-notebook"
  gem "jekyll-tabs"
end

gem "activesupport"
gem "nokogiri"
gem "open-uri"
