name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    container:
      image: jekyll/jekyll:4.3.2
    steps:
      - uses: actions/checkout@v4
      - name: Install bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
      - name: Build the site
        run: JEKYLL_ENV=production bundle exec jekyll build --trace
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: jekyll
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4

